/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Info */
        get: operations["health_info_api_v1_health_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_api_v1_employees_get"];
        put?: never;
        /** Add Employee */
        post: operations["add_employee_api_v1_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Directory Meta */
        get: operations["directory_meta_api_v1_employees_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_api_v1_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Employee */
        patch: operations["edit_employee_api_v1_employees__employee_id__patch"];
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/masters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Masters */
        get: operations["list_masters_api_v1_org_masters_get"];
        put?: never;
        /** Create Master */
        post: operations["create_master_api_v1_org_masters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/masters/{master_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Master */
        patch: operations["rename_master_api_v1_org_masters__master_id__patch"];
        trace?: never;
    };
    "/api/v1/org/masters/{master_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Master
         * @description Merge `master_id` INTO `into_master_id`: re-point all raw-value
         *     mappings, deactivate the source. ONAQT rows are untouched.
         */
        post: operations["merge_master_api_v1_org_masters__master_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Types */
        get: operations["list_types_api_v1_leave_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Balances */
        get: operations["my_balances_api_v1_leave_balances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_api_v1_leave_requests_get"];
        put?: never;
        /** Apply Leave */
        post: operations["apply_leave_api_v1_leave_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/{req_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_leave_requests__req_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/{req_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_v1_leave_requests__req_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/{req_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_leave_requests__req_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dev Login */
        post: operations["dev_login_api_v1_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEvent */
        AuditEvent: {
            /** Id */
            id: string;
            /** Actor Email */
            actor_email?: string | null;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Summary */
            summary?: string | null;
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BalanceOut */
        BalanceOut: {
            /** Leave Type Id */
            leave_type_id: string;
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Color */
            color: string;
            /** Entitled */
            entitled: string;
            /** Accrued */
            accrued: string;
            /** Carried Forward */
            carried_forward: string;
            /** Used */
            used: string;
            /** Pending */
            pending: string;
            /** Available */
            available: string;
        };
        /** Decision */
        Decision: {
            /** Note */
            note?: string | null;
        };
        /** DevSession */
        DevSession: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            /** User */
            user: {
                [key: string]: unknown;
            };
        };
        /**
         * DirectoryMeta
         * @description Existing values for form dropdowns (free text today; masters come later).
         */
        DirectoryMeta: {
            /** Departments */
            departments: string[];
            /** Divisions */
            divisions: string[];
            /** Branches */
            branches: string[];
            /** Designations */
            designations: string[];
            /** Circle Ids */
            circle_ids: number[];
        };
        /** DirectoryStats */
        DirectoryStats: {
            /** Total */
            total: number;
            /** Active */
            active: number;
            /** Probation */
            probation: number;
            /** Joining */
            joining: number;
            /** Notice */
            notice: number;
            /** Inactive */
            inactive: number;
            /** Departments */
            departments: string[];
        };
        /** EmployeeCreate */
        EmployeeCreate: {
            /** First Name */
            first_name: string;
            /** Middle Name */
            middle_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Employee Code */
            employee_code: string;
            /** Gender */
            gender?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Designation */
            designation: string;
            /** Department */
            department: string;
            /** Division */
            division: string;
            /** Branch */
            branch: string;
            /** Circle Id */
            circle_id: number;
            /** Reporting Manager Id */
            reporting_manager_id?: number | null;
            /**
             * Date Of Joining
             * Format: date
             */
            date_of_joining: string;
        };
        /** EmployeeDetail */
        EmployeeDetail: {
            /** Employee Id */
            employee_id: number;
            /** Employee Code */
            employee_code: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Designation */
            designation?: string | null;
            /** Department */
            department?: string | null;
            /** Branch */
            branch?: string | null;
            /** Manager Name */
            manager_name?: string | null;
            /** Date Of Joining */
            date_of_joining?: string | null;
            /** Tenure */
            tenure: string;
            /** Status */
            status: string;
            /** First Name */
            first_name: string;
            /** Middle Name */
            middle_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Gender */
            gender?: string | null;
            /** Division */
            division?: string | null;
            /** Circle Id */
            circle_id?: number | null;
            /** Reporting Manager Id */
            reporting_manager_id?: number | null;
            /** Date Of Leaving */
            date_of_leaving?: string | null;
            /** Fathers Name */
            fathers_name?: string | null;
            /** Mothers Name */
            mothers_name?: string | null;
            /** Marital Status */
            marital_status?: string | null;
            /** Spouse Name */
            spouse_name?: string | null;
            /** Alternate Phone */
            alternate_phone?: string | null;
            /** Pan No */
            pan_no?: string | null;
            /** Aadhaar No */
            aadhaar_no?: string | null;
            /**
             * Pii Visible
             * @default false
             */
            pii_visible: boolean;
        };
        /** EmployeeListItem */
        EmployeeListItem: {
            /** Employee Id */
            employee_id: number;
            /** Employee Code */
            employee_code: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Designation */
            designation?: string | null;
            /** Department */
            department?: string | null;
            /** Branch */
            branch?: string | null;
            /** Manager Name */
            manager_name?: string | null;
            /** Date Of Joining */
            date_of_joining?: string | null;
            /** Tenure */
            tenure: string;
            /** Status */
            status: string;
        };
        /** EmployeeListOut */
        EmployeeListOut: {
            /** Items */
            items: components["schemas"]["EmployeeListItem"][];
            /** Total Matches */
            total_matches: number;
            stats: components["schemas"]["DirectoryStats"];
        };
        /**
         * EmployeeUpdate
         * @description Partial update — only provided fields are written.
         */
        EmployeeUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Middle Name */
            middle_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Gender */
            gender?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Designation */
            designation?: string | null;
            /** Department */
            department?: string | null;
            /** Division */
            division?: string | null;
            /** Branch */
            branch?: string | null;
            /** Circle Id */
            circle_id?: number | null;
            /** Reporting Manager Id */
            reporting_manager_id?: number | null;
            /** Date Of Joining */
            date_of_joining?: string | null;
            /** Date Of Leaving */
            date_of_leaving?: string | null;
            /** Fathers Name */
            fathers_name?: string | null;
            /** Mothers Name */
            mothers_name?: string | null;
            /** Marital Status */
            marital_status?: string | null;
            /** Spouse Name */
            spouse_name?: string | null;
            /** Alternate Phone */
            alternate_phone?: string | null;
            /** Pan No */
            pan_no?: string | null;
            /** Aadhaar No */
            aadhaar_no?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthInfo */
        HealthInfo: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Employees Visible */
            employees_visible?: number | null;
        };
        /** LeaveApply */
        LeaveApply: {
            /** Leave Type Id */
            leave_type_id: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Half Day
             * @default false
             */
            half_day: boolean;
            /** Reason */
            reason?: string | null;
            /** Employee Id */
            employee_id?: number | null;
        };
        /** LeaveRequestOut */
        LeaveRequestOut: {
            /** Id */
            id: string;
            /** Employee Id */
            employee_id: number;
            /** Employee Name */
            employee_name: string;
            /** Leave Type Id */
            leave_type_id: string;
            /** Leave Code */
            leave_code: string;
            /** Leave Label */
            leave_label: string;
            /** Color */
            color: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Half Day */
            half_day: boolean;
            /** Days */
            days: string;
            /** Reason */
            reason?: string | null;
            /** Status */
            status: string;
            /** Approver Id */
            approver_id?: number | null;
            /** Approver Name */
            approver_name?: string | null;
            /** Decision Note */
            decision_note?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /**
             * Can Decide
             * @default false
             */
            can_decide: boolean;
            /**
             * Can Cancel
             * @default false
             */
            can_cancel: boolean;
        };
        /** LeaveTypeOut */
        LeaveTypeOut: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Color */
            color: string;
            /** Description */
            description?: string | null;
            /** Is Paid */
            is_paid: boolean;
            /** Accrual Method */
            accrual_method: string;
            /** Annual Entitlement */
            annual_entitlement: string;
            /** Min Advance Notice Days */
            min_advance_notice_days: number;
            /** Max Consecutive Days */
            max_consecutive_days?: number | null;
            /** Half Day Allowed */
            half_day_allowed: boolean;
            /** Requires Doc */
            requires_doc: boolean;
            /** Show In Ess */
            show_in_ess: boolean;
        };
        /** Liveness */
        Liveness: {
            /** Status */
            status: string;
        };
        /** MasterCreate */
        MasterCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "department" | "division" | "branch" | "designation";
            /** Name */
            name: string;
        };
        /** MasterMerge */
        MasterMerge: {
            /** Into Master Id */
            into_master_id: string;
        };
        /** MasterOut */
        MasterOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "department" | "division" | "branch" | "designation";
            /** Name */
            name: string;
            /** Raw Values */
            raw_values: string[];
            /** Employee Count */
            employee_count: number;
        };
        /** MasterRename */
        MasterRename: {
            /** Name */
            name: string;
        };
        /** MeOut */
        MeOut: {
            /** Employee Id */
            employee_id: number;
            /** Email */
            email: string;
            /** Roles */
            roles: string[];
            /** Persona */
            persona: string;
            /** Is Hr */
            is_hr: boolean;
        };
        /** Readiness */
        Readiness: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    health_info_api_v1_health_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthInfo"];
                };
            };
        };
    };
    list_employees_api_v1_employees_get: {
        parameters: {
            query?: {
                q?: string;
                department?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_employee_api_v1_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    directory_meta_api_v1_employees_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryMeta"];
                };
            };
        };
    };
    get_employee_api_v1_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_employee_api_v1_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_masters_api_v1_org_masters_get: {
        parameters: {
            query?: {
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_master_api_v1_org_masters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_master_api_v1_org_masters__master_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                master_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasterRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_master_api_v1_org_masters__master_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                master_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasterMerge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_types_api_v1_leave_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveTypeOut"][];
                };
            };
        };
    };
    my_balances_api_v1_leave_balances_get: {
        parameters: {
            query?: {
                employee_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_api_v1_leave_requests_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_leave_api_v1_leave_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveApply"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_leave_requests__req_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                req_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_leave_requests__req_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                req_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_leave_requests__req_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                req_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_audit_events_get: {
        parameters: {
            query?: {
                entity_type?: string;
                entity_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dev_login_api_v1_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevSession"];
                };
            };
        };
    };
}
